
version: '3.6'
services:
    nginx:
        build: docker/nginx
        ports:
            - '8080:80'
        volumes:
            - './:/usr/share/nginx/html'
    mariadb:
        image: 'mariadb:latest'
        environment:
            - MYSQL_DATABASE=docker
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=s3cr3t
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
    php-fpm:
        build: docker/php
        volumes:
            - './:/usr/share/nginx/html'
    composer:
        image: 'composer:1.8'
        command: install
        volumes:
            - './:/app'
